name: flutter_practice
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  animated_bottom_navigation_bar: ^1.4.0
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  kakao_flutter_sdk: ^1.9.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_padded.png

  android: true
  ios: true
  web: true

  ios_content_mode: scaleAspectFit
  android_gravity: center

  android_12:
    image: assets/images/logo_padded.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

  fullscreen: true